### ISSUE TITLE
sample in readme.md outdated

### ISSUE THREAD

**Issue by Merano01** [akboyd88/solar-edge-api-client#18]
some small problems with sample in readme.md:
1) interface was changed to use CompletionStage<OverviewResponse>, sample in ReadMe.md still shows CompletableFuture<OverviewResponse>
2) SolarEdgeClientFactory.builder() needs to initialize httpClient
3) add join() to give user a hint to wait for the async method
4) some syntax error with the lambda

this code is working for me:

`
    SolarEdgeClientFactory factory = SolarEdgeClientFactory.builder()
        .apiKey(YOUR_API_KEY) `
        .apiUrl("https://monitoringapi.solaredge.com")
`      .httpClient(HttpClient.newHttpClient()).build();`

    SolarEdgeApiClient client = factory.buildClient();
    
    CompletableFuture<OverviewResponse> future = client.getOverviewResponse(YOUR_SITE_NUMBER).toCompletableFuture();

    future.thenAcceptAsync(resp -> {
      System.out.println(String.format("Your solar panels are generating %s w/h of power",
          resp.getOverview().getCurrentPower().getPower()));
    });
    future.join();

**Comment by akboyd88** [comment]
merged in https://github.com/akboyd88/solar-edge-api-client/pull/19
